import re
import json
import logging
import asyncio
from enum import Enum
from typing import List, Dict, Optional, Any, Type

from pydantic import BaseModel, Field
from openai import AsyncOpenAI, RateLimitError, APIConnectionError, APITimeoutError
from tenacity import retry, stop_after_attempt, wait_fixed, retry_if_exception_type
from qdrant_client import AsyncQdrantClient

# Import your actual models here to dynamically extract schemas
from core.models.node import Node, ModalityCategory, Granularity
from core.models.edge import Edge, EdgeCategory

# Try to import json_repair for handling broken LLM JSON outputs
try:
    from json_repair import repair_json
    HAS_JSON_REPAIR = True
except ImportError:
    HAS_JSON_REPAIR = False

logger = logging.getLogger(__name__)

# ==========================================
# Pydantic Models for the Structured Output
# ==========================================

class RetrievalPlan(BaseModel):
    """The structured output generated by the SLM for the Retriever to execute."""
    intent_summary: str = Field(description="A 1-sentence rewritten version of the user's query optimized for vector search.")
    query_type: str = Field(description="One of: 'specific_lookup', 'spatial_relational', 'broad_summary'")
    
    target_modalities: List[str] = Field(description="List of ModalityCategory string values to filter in Qdrant")
    target_granularities: List[str] = Field(description="List of Granularity string values to filter in Qdrant (e.g., ['section', 'element'])")
    filter_edges: List[str] = Field(description="List of EdgeCategory string values to traverse in Neo4j")
    
    high_confidence_node_ids: List[str] = Field(default_factory=list, description="UUIDs of sections/nodes from the TOC that are highly relevant")
    high_confidence_weight: float = Field(default=1.5, ge=1.0, le=2.0, description="Weight multiplier to boost scores of nodes in high_confidence_node_ids")
    
    # Future-proofing for Phase 3.2 Community Detection
    use_community_nodes: bool = Field(default=False, description="Set to True if the query asks for a broad summary of the whole document/concept")


class QueryRouter:
    """
    Phase 4.1: SLM-Driven Query Routing.
    Analyzes the user query, maps it to the document schema, and generates a RetrievalPlan.
    """
    
    def __init__(
        self, 
        qdrant_client: AsyncQdrantClient,
        embedding_model: str = "text-embedding-3-small",
        slm_model: str = "llama3.1:8b-instruct-q4_K_M",
        qdrant_node_collection: str = "nodes",
        # LLM Config
        llm_base_url: str = "http://localhost:11434/v1",
        llm_api_key: str = "ollama",
        # Embedder Config (Separate sources allowed)
        embed_base_url: str = "https://api.openai.com/v1",
        embed_api_key: str = "your-openai-api-key"
    ):
        self.qdrant_client = qdrant_client
        self.embedding_model = embedding_model
        self.qdrant_node_collection = qdrant_node_collection
        
        self.slm_model = slm_model
        
        # Initialize separate clients for LLM and Embedder
        self.llm_client = AsyncOpenAI(base_url=llm_base_url, api_key=llm_api_key, timeout=30.0, max_retries=0)
        self.embed_client = AsyncOpenAI(base_url=embed_base_url, api_key=embed_api_key, timeout=30.0, max_retries=0)
        
        # Dynamically extract schemas at initialization
        self.node_modalities = self._extract_enum_values(ModalityCategory)
        self.edge_categories = self._extract_enum_values(EdgeCategory)
        self.granularities = self._extract_enum_values(Granularity)

    def _extract_enum_values(self, enum_class: Type[Enum]) -> List[str]:
        """Dynamically extracts string values from an Enum class."""
        return [e.value for e in enum_class]

    async def route(self, user_query: str, tenant_id: str = "default", doc_id: Optional[str] = None) -> RetrievalPlan:
        """Main entry point for routing a query."""
        logger.info(f"Routing query: '{user_query}'")
        
        # 1. Fetch Dynamic TOC (Table of Contents) from Qdrant using Vector Search
        toc_context, toc_ids = await self._fetch_dynamic_toc(user_query, tenant_id, doc_id)
        
        # 2. Generate SLM Prompt
        messages = self._build_prompt(user_query, toc_context)
        
        # 3. Call SLM and Parse Output
        plan = await self._call_slm(messages, user_query, toc_ids)
        return plan

    @retry(
        retry=retry_if_exception_type((RateLimitError, APIConnectionError, APITimeoutError)),
        stop=stop_after_attempt(3),
        wait=wait_fixed(2)
    )
    async def _embed_query(self, text: str) -> List[float]:
        """Embeds the user query using the configured embedder API."""
        response = await self.embed_client.embeddings.create(
            model=self.embedding_model,
            input=text
        )
        return response.data[0].embedding

    async def _fetch_dynamic_toc(self, query: str, tenant_id: str, doc_id: Optional[str]) -> tuple[str, List[str]]:
        """
        Queries Qdrant for high-level structural nodes (Sections, Pages) 
        to act as a dynamic Table of Contents context for the SLM.
        """
        try:
            query_vector = await self._embed_query(query)
            
            # We only want high-level structural nodes for the TOC
            must_filters = [
                {"key": "tenant_id", "match": {"value": tenant_id}},
                {"key": "granularity", "match": {"any": ["section", "root", "page"]}}
            ]
            if doc_id:
                must_filters.append({"key": "doc_id", "match": {"value": doc_id}})
                
            results = await self.qdrant_client.search(
                collection_name=self.qdrant_node_collection,
                query_vector=query_vector,
                query_filter={"must": must_filters},
                limit=10,
                with_payload=True
            )
            
            if not results:
                return "No table of contents available.", []
                
            toc_items = []
            toc_ids = []
            for point in results:
                payload = point.payload or {}
                title = payload.get("content", "Unknown Section").split('\n')[0]
                toc_items.append(f"- ID: {point.id} | Title: {title} (Score: {point.score:.2f})")
                toc_ids.append(str(point.id))
                
            return "Document Table of Contents (High-Level Sections):\n" + "\n".join(toc_items), toc_ids
            
        except Exception as e:
            logger.warning(f"Failed to fetch dynamic TOC from Qdrant: {e}")
            return "No table of contents available.", []

    def _build_prompt(self, user_query: str, toc_context: str) -> List[Dict]:
        """Builds the system and user prompts for the SLM."""
        
        system_prompt = f"""You are an expert query routing agent for a Graph RAG database. 
Your job is to analyze a user's natural language query and output a strict JSON retrieval plan.

Available Node Modality Categories (use EXACTLY these strings for target_modalities):
{json.dumps(self.node_modalities)}

Available Node Granularities (use EXACTLY these strings for target_granularities):
{json.dumps(self.granularities)}

Available Edge Categories (use EXACTLY these strings for filter_edges):
{json.dumps(self.edge_categories)}

Routing Rules:
1. `intent_summary`: Rewrite the user query to be optimal for dense vector search (remove conversational filler, focus on entities).
2. `query_type`: 
   - 'specific_lookup': Asking for a specific data point (e.g., "What is the pressure of V-101?").
   - 'spatial_relational': Asking about layout or proximity (e.g., "What is left of the reactor?").
   - 'broad_summary': Asking for a holistic summary (e.g., "What is this document about?"). Set `use_community_nodes` to true ONLY for this type.
3. `target_modalities`: Which node types to vector search. If asking about a table, include 'table_container'. If asking about text, include 'textual_content'.
4. `target_granularities`: If asking for a summary, include ['section', 'root']. If asking for specific data, include ['element', 'block'].
5. `filter_edges`: Which graph edges to traverse. For spatial questions, include 'spatial_relation'. For specific lookups, include 'hierarchy'. NEVER include 'read_order'.
6. `high_confidence_node_ids`: If the user query explicitly matches a section title from the Table of Contents provided, put that section's ID here.

Output STRICTLY valid JSON. No markdown formatting, no explanations."""

        user_prompt = f"""User Query: "{user_query}"

Table of Contents Context:
{toc_context}

Generate the JSON retrieval plan now."""

        return [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]

    @retry(
        retry=retry_if_exception_type((RateLimitError, APIConnectionError, APITimeoutError)),
        stop=stop_after_attempt(3),
        wait=wait_fixed(2)
    )
    async def _call_slm(self, messages: List[Dict], original_query: str, toc_ids: List[str]) -> RetrievalPlan:
        """Calls the SLM and parses the JSON response into a RetrievalPlan."""
        try:
            response = await self.llm_client.chat.completions.create(
                model=self.slm_model,
                messages=messages,
                temperature=0.1,
                response_format={"type": "json_object"} # Force JSON mode
            )
            
            content = response.choices[0].message.content
            if not content:
                raise ValueError("SLM returned empty response")
                
            # Clean markdown if present
            content = re.sub(r'^```(?:json)?\s*', '', content.strip())
            content = re.sub(r'\s*```$', '', content.strip())
            
            # Parse JSON (use json_repair if available for broken 8B model outputs)
            if HAS_JSON_REPAIR:
                plan_dict = repair_json(content, return_objects=True)
            else:
                plan_dict = json.loads(content)
            
            # Validate with Pydantic
            plan = RetrievalPlan(**plan_dict)
            
            # Fallback: If SLM forgot to add TOC ids but they are highly relevant, inject them
            if not plan.high_confidence_node_ids and toc_ids:
                plan.high_confidence_node_ids = toc_ids[:3] # Take top 3 TOC matches
                
            logger.info(f"Successfully generated retrieval plan. Intent: {plan.intent_summary}")
            return plan
            
        except Exception as e:
            logger.error(f"SLM routing failed: {e}. Falling back to default plan.")
            # Fallback plan
            return RetrievalPlan(
                intent_summary=original_query,
                query_type="specific_lookup",
                target_modalities=["textual_content", "table_container"],
                target_granularities=["element", "block"],
                filter_edges=["hierarchy", "reference"],
                high_confidence_node_ids=toc_ids[:3],
                use_community_nodes=False
            )

# ==========================================
# Example Usage (For testing)
# ==========================================
async def test_router():
    from qdrant_client import AsyncQdrantClient
    qdrant = AsyncQdrantClient(url="http://localhost:6333")
    
    router = QueryRouter(
        qdrant_client=qdrant,
        slm_model="llama3.1:8b-instruct-q4_K_M",
        # LLM Config (Local Ollama)
        llm_base_url="http://localhost:11434/v1",
        llm_api_key="ollama",
        # Embedder Config (Cloud OpenAI)
        embedding_model="text-embedding-3-small",
        embed_base_url="https://api.openai.com/v1",
        embed_api_key="sk-proj-..."
    )
    
    queries = [
        "What is the table next to the Reactor section?",
        "Give me a summary of the entire document",
        "Find the specifications for Valve V-101"
    ]
    
    for q in queries:
        print(f"\nQuery: {q}")
        try:
            plan = await router.route(q, tenant_id="default")
            print(json.dumps(plan.model_dump(), indent=2))
        except Exception as e:
            print(f"Error: {e}")

if __name__ == "__main__":
    asyncio.run(test_router())